Add Multiple Argument Functionality to STLC Interface
anoma/geb pull request #115
Opened 2023-05-03 13:28 UTC by agureev

This commit adds following functionality:

1) `lamb` now accepts a list of types for its `tdom` accessor allowing for functions to be defined in a complex context. The domain of such a lambda term will then be the iterated product.

2) 'app' now accepts a list of terms for its `term` accessor allowing for a multi-argument function to be iteratively applied.

3) Change `index` functionality to follow usual convention of reading contexts from left to right.

4) Change the STLC -> GEB compilation to be uncurried solving #106 and allowing for a neater solution to #90

2023-05-04 09:54 UTC, agureev commented
Adding @rokopt as a new reviewer to receive approval on the new compilation pass. Note that the application interpretation follows from composition-as-substitution definition in the term model.

2023-05-05 04:46 UTC, mariari requested changes
I'd like to see updated docs on the classes. Since the semantics of lambda and app changed, I wish for the class documentation to be updated to reflect this, and type signatures added to the classes and constructors as well, so I can see them at a glance.

Overall after some docs changes I did manually the pr seems to work, I want the HOF example put into a test as well

2023-05-05 04:46 UTC, mariari commented on src/util/utils.lisp
> +      (setf value (funcall f value)))))
Probably would good to have a doc string with this

2023-05-05 04:46 UTC, mariari commented on src/lambda/lambda.lisp
> +        (error "Argument exceeds length of context"))))
Yeah much nicer

2023-05-05 04:46 UTC, mariari commented on src/lambda/lambda.lisp
> +        ((lamb tdom term)   (let ((ant (ann-term1 (append tdom ctx) term)))
This causes tests to fail, as tdom is still so1 in some situations

2023-05-05 04:46 UTC, mariari commented on src/lambda/lambda.lisp
> +        ((lamb tdom term)   (let ((ant (ann-term1 (append tdom ctx) term)))
With the merged commits this is no longer an issue

2023-05-05 04:46 UTC, mariari commented on src/lambda/lambda.lisp
> +                (ann-left   (ann-term1 (cons  (mcar type-of-on) ctx) ltm))
Seems like a needless change that makes formatting worse

2023-05-05 04:46 UTC, mariari commented on src/lambda/trans.lisp
> +                (comp  (rec context fun)
change

```lisp
(comp  (rec context fun) ...)
```

into

```lisp
(comp (rec context fun) ...)

2023-05-05 04:46 UTC, mariari commented on src/specs/lambda.lisp
> +gotten in the context to whom we append the list of the domains.
Some of these docs need to propagate into the class docs

2023-05-07 20:32 UTC, rokopt approved these changes
This makes sense to me -- thank you!

As a general comment:  I suggest we ask the Juvix team how much it'll take for them to adapt to the change to the indexing; if it's at all difficult then we could provide a utility that just syntactically transforms a program written with the old indexing to one written with the new.

2023-05-07 20:38 UTC, merged